version: '3'

services:
  redis:

    image: redis:alpine
    container_name: caching
    networks:
      - api-net
    restart: always

  ipstack1:

    image: freedafrancis/ipstack-app:latest
    container_name: ipstack-app1
    networks:
      - api-net
    restart: always
    ports:
      - "8081:8080"
    environment:
      - CACHING_SERVER=caching
      - IPSTACK_KEY=${IPSTACK_KEY}

  ipstack2:

    image: freedafrancis/ipstack-app:latest
    container_name: ipstack-app2
    networks:
      - api-net
    restart: always
    ports:
      - "8082:8080"
    environment:
      - CACHING_SERVER=caching
      - IPSTACK_KEY=${IPSTACK_KEY}
  ipstack3:

    image: freedafrancis/ipstack-app:latest
    container_name: ipstack-app3
    networks:
      - api-net
    restart: always
    ports:
      - "8083:8080"
    environment:
      - CACHING_SERVER=caching
      - IPSTACK_KEY=${IPSTACK_KEY}
networks:
  api-net:
